
# A string used to distinguish different Supabase projects on the same host. 
# This is the project id of your Supabase project.
project_id = "ujqnfwwkekgpygkybadn"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. 
# Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL
port = 54322
# Port used by the local database for connecting via TCP
server_port = 5432
# The database major version to use. This has to be the same as your remote database's.
# default is 15
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323
# External URL of the API server that frontend connects to
api_url = "https://ujqnfwwkekgpygkybadn.supabase.co"

# Email testing server. Emails sent with the local dev setup are not actually sent - the 
# server catches the emails and outputs the emails to the console.
[inbucket]
# Port to use for the email testing server web interface
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Configure one of the supported SMS providers: twilio, messagebird, textlocal, vonage, or disable entirely.
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

# Use an external OAuth provider. The full list of providers are: apple, azure, bitbucket,
# discord, facebook, github, gitlab, google, keycloak, linkedin, notion, twitch, twitter,
# slack, spotify, workos, zoom.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: postgres, bigquery, snowflake
backend = "postgres"

# Configures Postgres backend
[analytics.postgres]
# in seconds, defaults to 24h
analytics_retention_days = 90

# Configures BigQuery backend
[analytics.bigquery]
# Path to the service account JSON credentials file
service_account_json_path = ""
# Set the dataset ID
dataset_id = ""
# Set the BigQuery project ID
# If left blank, will default to using the service account's project
# project_id = ""
# in days, defaults to 90 days
analytics_retention_days = 90

# Configures Snowflake backend
[analytics.snowflake]
username = ""
password = ""
account = ""
database = ""
warehouse = ""
schema = ""
# in days, defaults to 90 days
analytics_retention_days = 90

[functions]
port = 54321
function_timeout_seconds = 30
enabled = true

[functions.collection-operations]
verify_jwt = true
