// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujqnfwwkekgpygkybadn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcW5md3drZWtncHlna3liYWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTk0MjYsImV4cCI6MjA2MDYzNTQyNn0.zMcPAOaQ2QZ5tknhepeqKKXqtPIvpZ8rRWWxV4lQfYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);